import type { NextPage } from "next";
import Head from "next/head";

import Header from "../components/shared/header";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>RLE</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header></Header>

      <main className={styles.main}>
        <h1 className={styles.title}>RLE</h1>
        <h2 className={styles.subtitle}>Conoce el curso</h2>
      </main>
    </div>
  );
};

export default Home;
