import type { NextPage } from "next";
import Head from "next/head";

import Header from "../components/shared/header";
import styles from "../styles/Perfil.module.css";

const Perfil: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Perfil - RLE</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header></Header>

      <main className={styles.main}>
        <h1 className={styles.title}>Selecciona tu perfil</h1>

        <div className="container mt-5">
          <div className="row justify-content-md-center">
            <div
              className={
                "col col-lg-3 border border-dark" + " " + styles.quadrate
              }
            >
              <h2 className={styles.subtitle}>Nuevo viajero</h2>
              <p>Aún no has llevado el curso y estás preparándote para ello</p>
            </div>
            <div className="col col-lg-1 mx-5"></div>
            <div
              className={
                "col col-lg-3 border border-dark" + " " + styles.quadrate
              }
            >
              <h2 className={styles.subtitle}>Tripulante</h2>
              <p>
                Estás matriculado en el curso y deseas conocer la información
                necesaria durante el viaje
              </p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Perfil;
